# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa328d59b6732a340f1c4e5a771b3cc2700998fe69524fbcd1027a8e40016634243b7010f3b20ab016ebf90d4ccac8a76008e3363db6888668ec222ac6a59b7d

test:
  secret_key_base: e47e057d92c9329607243a114f7bc80e83af9927f77cc98549eadf56e0a997468efc0c8dcc169bbafd34e861a50bed0aa26a856a50cd7b1f53c48ae861622cef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
